/********************************************************************************
** Form generated from reading UI file 'locateWidget.ui'
**
** Created by: Qt User Interface Compiler version 5.15.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LOCATEWIDGET_H
#define UI_LOCATEWIDGET_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_locateWidgetClass
{
public:
    QGroupBox *groupBoxInit;
    QPushButton *btnOpenCADPointCloud;
    QPushButton *btnCapturePointCloud;
    QCheckBox *checkBoxTestPointCloud;
    QGroupBox *groupBoxRegisPara;
    QComboBox *comboBoxRegisMethod;
    QComboBox *comboBoxPreciseRegisMethod;
    QComboBox *comboBoxRoughRegisMethod;
    QGroupBox *groupBoxRegisControl;
    QPushButton *btnStartRoughRegis;
    QPushButton *btnStartPreciseRegis;
    QGroupBox *groupBoxPointCloudPreProcess;
    QPushButton *btnDownsample;
    QPushButton *btnFilter;
    QDoubleSpinBox *numFilterRadius;
    QLabel *labelRadius;
    QLabel *labelMinNeighborsInRadius;
    QDoubleSpinBox *numFilterMinNeighborsInRadius;
    QDoubleSpinBox *numSourceDownsample;
    QLabel *labelDownsample;
    QLabel *labelDownsample_2;
    QDoubleSpinBox *numTargetDownsample;
    QWidget *widgetFPCS;
    QDoubleSpinBox *FPCSNumberOfSamples;
    QLabel *labelMaximumIterations_6;
    QDoubleSpinBox *FPCSOverlapRate;
    QDoubleSpinBox *FPCSEpsilon;
    QLabel *labelNormalRadius_6;
    QLabel *labelTransformationEpsilon_6;
    QLabel *labelEuclideanEpsilon_6;
    QDoubleSpinBox *FPCSMaxIterations;
    QDoubleSpinBox *FPCSDelta;
    QLabel *labelMaxCorrespondenceDistance_6;
    QDoubleSpinBox *FPCSNumberOfThreads;
    QLabel *labelNormalRadius_9;
    QWidget *widgetKFPCS;
    QDoubleSpinBox *KFPCSNumberOfSamples;
    QLabel *labelKFPCSDelta;
    QDoubleSpinBox *KFPCSOverlapRate;
    QDoubleSpinBox *KFPCSEpsilon;
    QLabel *labelNormalRadius_7;
    QLabel *labelTransformationEpsilon_7;
    QLabel *labelEuclideanEpsilon_7;
    QDoubleSpinBox *KFPCSMaxIterations;
    QDoubleSpinBox *KFPCSDelta;
    QLabel *labelMaxCorrespondenceDistance_7;
    QDoubleSpinBox *KFPCSLambda;
    QLabel *labelNormalRadius_11;
    QDoubleSpinBox *KFPCSMaxAngleDiff;
    QLabel *labelNormalRadius_12;
    QWidget *widgetSFPCS;
    QDoubleSpinBox *SFPCSNumberOfSamples;
    QLabel *labelMaximumIterations_8;
    QDoubleSpinBox *SFPCSOverlapRate;
    QDoubleSpinBox *SFPCSEpsilon;
    QLabel *labelNormalRadius_8;
    QLabel *labelTransformationEpsilon_8;
    QLabel *labelEuclideanEpsilon_8;
    QDoubleSpinBox *SFPCSMaxIterations;
    QDoubleSpinBox *SFPCSDelta;
    QLabel *labelMaxCorrespondenceDistance_8;
    QDoubleSpinBox *SFPCSMaxTime;
    QLabel *labelNormalRadius_13;
    QWidget *widgetNICP;
    QDoubleSpinBox *NICPNormalRadius;
    QLabel *labelMaximumIterations_9;
    QDoubleSpinBox *NICPMaxDistance;
    QDoubleSpinBox *NICPMaxIterations;
    QLabel *labelNICPNormalRadius;
    QLabel *labelTransformationEpsilon_9;
    QLabel *labelEuclideanEpsilon_9;
    QDoubleSpinBox *NICPTransEpsilon;
    QDoubleSpinBox *NICPEulideanEpsilon;
    QLabel *labelMaxCorrespondenceDistance_9;
    QWidget *widgetICP;
    QLabel *labelICPEulideanEpsilon;
    QDoubleSpinBox *ICPMaxDistance;
    QDoubleSpinBox *ICPMaxIterations;
    QLabel *labelTransformationEpsilon_12;
    QLabel *labelEuclideanEpsilon_12;
    QDoubleSpinBox *ICPTransEpsilon;
    QDoubleSpinBox *ICPEulideanEpsilon;
    QLabel *labelMaxCorrespondenceDistance_12;

    void setupUi(QWidget *locateWidgetClass)
    {
        if (locateWidgetClass->objectName().isEmpty())
            locateWidgetClass->setObjectName(QString::fromUtf8("locateWidgetClass"));
        locateWidgetClass->resize(252, 792);
        groupBoxInit = new QGroupBox(locateWidgetClass);
        groupBoxInit->setObjectName(QString::fromUtf8("groupBoxInit"));
        groupBoxInit->setGeometry(QRect(10, 10, 231, 131));
        btnOpenCADPointCloud = new QPushButton(groupBoxInit);
        btnOpenCADPointCloud->setObjectName(QString::fromUtf8("btnOpenCADPointCloud"));
        btnOpenCADPointCloud->setGeometry(QRect(20, 20, 91, 41));
        btnCapturePointCloud = new QPushButton(groupBoxInit);
        btnCapturePointCloud->setObjectName(QString::fromUtf8("btnCapturePointCloud"));
        btnCapturePointCloud->setGeometry(QRect(20, 70, 91, 41));
        checkBoxTestPointCloud = new QCheckBox(groupBoxInit);
        checkBoxTestPointCloud->setObjectName(QString::fromUtf8("checkBoxTestPointCloud"));
        checkBoxTestPointCloud->setGeometry(QRect(120, 80, 101, 16));
        groupBoxRegisPara = new QGroupBox(locateWidgetClass);
        groupBoxRegisPara->setObjectName(QString::fromUtf8("groupBoxRegisPara"));
        groupBoxRegisPara->setGeometry(QRect(10, 410, 231, 281));
        comboBoxRegisMethod = new QComboBox(groupBoxRegisPara);
        comboBoxRegisMethod->addItem(QString());
        comboBoxRegisMethod->addItem(QString());
        comboBoxRegisMethod->setObjectName(QString::fromUtf8("comboBoxRegisMethod"));
        comboBoxRegisMethod->setGeometry(QRect(20, 20, 71, 22));
        comboBoxPreciseRegisMethod = new QComboBox(groupBoxRegisPara);
        comboBoxPreciseRegisMethod->addItem(QString());
        comboBoxPreciseRegisMethod->addItem(QString());
        comboBoxPreciseRegisMethod->setObjectName(QString::fromUtf8("comboBoxPreciseRegisMethod"));
        comboBoxPreciseRegisMethod->setGeometry(QRect(110, 20, 101, 22));
        comboBoxRoughRegisMethod = new QComboBox(groupBoxRegisPara);
        comboBoxRoughRegisMethod->addItem(QString());
        comboBoxRoughRegisMethod->addItem(QString());
        comboBoxRoughRegisMethod->addItem(QString());
        comboBoxRoughRegisMethod->setObjectName(QString::fromUtf8("comboBoxRoughRegisMethod"));
        comboBoxRoughRegisMethod->setGeometry(QRect(110, 20, 101, 22));
        groupBoxRegisControl = new QGroupBox(locateWidgetClass);
        groupBoxRegisControl->setObjectName(QString::fromUtf8("groupBoxRegisControl"));
        groupBoxRegisControl->setGeometry(QRect(10, 700, 231, 81));
        btnStartRoughRegis = new QPushButton(groupBoxRegisControl);
        btnStartRoughRegis->setObjectName(QString::fromUtf8("btnStartRoughRegis"));
        btnStartRoughRegis->setGeometry(QRect(20, 20, 91, 41));
        btnStartPreciseRegis = new QPushButton(groupBoxRegisControl);
        btnStartPreciseRegis->setObjectName(QString::fromUtf8("btnStartPreciseRegis"));
        btnStartPreciseRegis->setGeometry(QRect(120, 20, 91, 41));
        groupBoxPointCloudPreProcess = new QGroupBox(locateWidgetClass);
        groupBoxPointCloudPreProcess->setObjectName(QString::fromUtf8("groupBoxPointCloudPreProcess"));
        groupBoxPointCloudPreProcess->setGeometry(QRect(10, 150, 231, 251));
        btnDownsample = new QPushButton(groupBoxPointCloudPreProcess);
        btnDownsample->setObjectName(QString::fromUtf8("btnDownsample"));
        btnDownsample->setGeometry(QRect(20, 190, 91, 41));
        btnFilter = new QPushButton(groupBoxPointCloudPreProcess);
        btnFilter->setObjectName(QString::fromUtf8("btnFilter"));
        btnFilter->setGeometry(QRect(20, 80, 91, 41));
        numFilterRadius = new QDoubleSpinBox(groupBoxPointCloudPreProcess);
        numFilterRadius->setObjectName(QString::fromUtf8("numFilterRadius"));
        numFilterRadius->setGeometry(QRect(120, 20, 101, 22));
        numFilterRadius->setDecimals(5);
        numFilterRadius->setMaximum(100.000000000000000);
        numFilterRadius->setSingleStep(0.100000000000000);
        numFilterRadius->setValue(5.000000000000000);
        labelRadius = new QLabel(groupBoxPointCloudPreProcess);
        labelRadius->setObjectName(QString::fromUtf8("labelRadius"));
        labelRadius->setGeometry(QRect(20, 20, 81, 16));
        labelMinNeighborsInRadius = new QLabel(groupBoxPointCloudPreProcess);
        labelMinNeighborsInRadius->setObjectName(QString::fromUtf8("labelMinNeighborsInRadius"));
        labelMinNeighborsInRadius->setGeometry(QRect(20, 50, 81, 16));
        numFilterMinNeighborsInRadius = new QDoubleSpinBox(groupBoxPointCloudPreProcess);
        numFilterMinNeighborsInRadius->setObjectName(QString::fromUtf8("numFilterMinNeighborsInRadius"));
        numFilterMinNeighborsInRadius->setGeometry(QRect(120, 50, 101, 22));
        numFilterMinNeighborsInRadius->setDecimals(5);
        numFilterMinNeighborsInRadius->setMaximum(100.000000000000000);
        numFilterMinNeighborsInRadius->setSingleStep(0.100000000000000);
        numFilterMinNeighborsInRadius->setValue(15.000000000000000);
        numSourceDownsample = new QDoubleSpinBox(groupBoxPointCloudPreProcess);
        numSourceDownsample->setObjectName(QString::fromUtf8("numSourceDownsample"));
        numSourceDownsample->setGeometry(QRect(120, 130, 101, 22));
        numSourceDownsample->setDecimals(5);
        numSourceDownsample->setMaximum(1000.000000000000000);
        numSourceDownsample->setSingleStep(1.000000000000000);
        numSourceDownsample->setValue(15.000000000000000);
        labelDownsample = new QLabel(groupBoxPointCloudPreProcess);
        labelDownsample->setObjectName(QString::fromUtf8("labelDownsample"));
        labelDownsample->setGeometry(QRect(20, 130, 91, 16));
        labelDownsample_2 = new QLabel(groupBoxPointCloudPreProcess);
        labelDownsample_2->setObjectName(QString::fromUtf8("labelDownsample_2"));
        labelDownsample_2->setGeometry(QRect(20, 160, 91, 16));
        numTargetDownsample = new QDoubleSpinBox(groupBoxPointCloudPreProcess);
        numTargetDownsample->setObjectName(QString::fromUtf8("numTargetDownsample"));
        numTargetDownsample->setGeometry(QRect(120, 160, 101, 22));
        numTargetDownsample->setDecimals(5);
        numTargetDownsample->setMaximum(100.000000000000000);
        numTargetDownsample->setSingleStep(1.000000000000000);
        numTargetDownsample->setValue(15.000000000000000);
        widgetFPCS = new QWidget(locateWidgetClass);
        widgetFPCS->setObjectName(QString::fromUtf8("widgetFPCS"));
        widgetFPCS->setGeometry(QRect(260, 20, 211, 221));
        FPCSNumberOfSamples = new QDoubleSpinBox(widgetFPCS);
        FPCSNumberOfSamples->setObjectName(QString::fromUtf8("FPCSNumberOfSamples"));
        FPCSNumberOfSamples->setGeometry(QRect(110, 130, 91, 22));
        FPCSNumberOfSamples->setDecimals(5);
        FPCSNumberOfSamples->setMaximum(10000.000000000000000);
        FPCSNumberOfSamples->setSingleStep(1.000000000000000);
        FPCSNumberOfSamples->setValue(200.000000000000000);
        labelMaximumIterations_6 = new QLabel(widgetFPCS);
        labelMaximumIterations_6->setObjectName(QString::fromUtf8("labelMaximumIterations_6"));
        labelMaximumIterations_6->setGeometry(QRect(10, 10, 91, 16));
        FPCSOverlapRate = new QDoubleSpinBox(widgetFPCS);
        FPCSOverlapRate->setObjectName(QString::fromUtf8("FPCSOverlapRate"));
        FPCSOverlapRate->setGeometry(QRect(110, 100, 91, 22));
        FPCSOverlapRate->setDecimals(5);
        FPCSOverlapRate->setMaximum(10.000000000000000);
        FPCSOverlapRate->setSingleStep(0.100000000000000);
        FPCSOverlapRate->setValue(0.900000000000000);
        FPCSEpsilon = new QDoubleSpinBox(widgetFPCS);
        FPCSEpsilon->setObjectName(QString::fromUtf8("FPCSEpsilon"));
        FPCSEpsilon->setGeometry(QRect(110, 40, 91, 22));
        FPCSEpsilon->setDecimals(5);
        FPCSEpsilon->setMaximum(10.000000000000000);
        FPCSEpsilon->setSingleStep(0.000100000000000);
        FPCSEpsilon->setValue(0.000100000000000);
        labelNormalRadius_6 = new QLabel(widgetFPCS);
        labelNormalRadius_6->setObjectName(QString::fromUtf8("labelNormalRadius_6"));
        labelNormalRadius_6->setGeometry(QRect(10, 130, 91, 16));
        labelTransformationEpsilon_6 = new QLabel(widgetFPCS);
        labelTransformationEpsilon_6->setObjectName(QString::fromUtf8("labelTransformationEpsilon_6"));
        labelTransformationEpsilon_6->setGeometry(QRect(10, 100, 91, 20));
        labelEuclideanEpsilon_6 = new QLabel(widgetFPCS);
        labelEuclideanEpsilon_6->setObjectName(QString::fromUtf8("labelEuclideanEpsilon_6"));
        labelEuclideanEpsilon_6->setGeometry(QRect(10, 40, 91, 16));
        FPCSMaxIterations = new QDoubleSpinBox(widgetFPCS);
        FPCSMaxIterations->setObjectName(QString::fromUtf8("FPCSMaxIterations"));
        FPCSMaxIterations->setGeometry(QRect(110, 70, 91, 22));
        FPCSMaxIterations->setDecimals(0);
        FPCSMaxIterations->setMaximum(10000.000000000000000);
        FPCSMaxIterations->setSingleStep(0.001000000000000);
        FPCSMaxIterations->setValue(200.000000000000000);
        FPCSDelta = new QDoubleSpinBox(widgetFPCS);
        FPCSDelta->setObjectName(QString::fromUtf8("FPCSDelta"));
        FPCSDelta->setGeometry(QRect(110, 10, 91, 22));
        FPCSDelta->setDecimals(5);
        FPCSDelta->setMaximum(1000.000000000000000);
        FPCSDelta->setSingleStep(0.100000000000000);
        FPCSDelta->setValue(0.500000000000000);
        labelMaxCorrespondenceDistance_6 = new QLabel(widgetFPCS);
        labelMaxCorrespondenceDistance_6->setObjectName(QString::fromUtf8("labelMaxCorrespondenceDistance_6"));
        labelMaxCorrespondenceDistance_6->setGeometry(QRect(10, 70, 91, 16));
        FPCSNumberOfThreads = new QDoubleSpinBox(widgetFPCS);
        FPCSNumberOfThreads->setObjectName(QString::fromUtf8("FPCSNumberOfThreads"));
        FPCSNumberOfThreads->setGeometry(QRect(110, 160, 91, 22));
        FPCSNumberOfThreads->setDecimals(5);
        FPCSNumberOfThreads->setMaximum(100.000000000000000);
        FPCSNumberOfThreads->setSingleStep(1.000000000000000);
        FPCSNumberOfThreads->setValue(4.000000000000000);
        labelNormalRadius_9 = new QLabel(widgetFPCS);
        labelNormalRadius_9->setObjectName(QString::fromUtf8("labelNormalRadius_9"));
        labelNormalRadius_9->setGeometry(QRect(10, 160, 91, 16));
        widgetKFPCS = new QWidget(locateWidgetClass);
        widgetKFPCS->setObjectName(QString::fromUtf8("widgetKFPCS"));
        widgetKFPCS->setGeometry(QRect(490, 20, 211, 221));
        KFPCSNumberOfSamples = new QDoubleSpinBox(widgetKFPCS);
        KFPCSNumberOfSamples->setObjectName(QString::fromUtf8("KFPCSNumberOfSamples"));
        KFPCSNumberOfSamples->setGeometry(QRect(110, 130, 91, 22));
        KFPCSNumberOfSamples->setDecimals(5);
        KFPCSNumberOfSamples->setMaximum(10000.000000000000000);
        KFPCSNumberOfSamples->setSingleStep(1.000000000000000);
        KFPCSNumberOfSamples->setValue(500.000000000000000);
        labelKFPCSDelta = new QLabel(widgetKFPCS);
        labelKFPCSDelta->setObjectName(QString::fromUtf8("labelKFPCSDelta"));
        labelKFPCSDelta->setGeometry(QRect(10, 10, 91, 16));
        KFPCSOverlapRate = new QDoubleSpinBox(widgetKFPCS);
        KFPCSOverlapRate->setObjectName(QString::fromUtf8("KFPCSOverlapRate"));
        KFPCSOverlapRate->setGeometry(QRect(110, 100, 91, 22));
        KFPCSOverlapRate->setDecimals(5);
        KFPCSOverlapRate->setMaximum(10.000000000000000);
        KFPCSOverlapRate->setSingleStep(0.100000000000000);
        KFPCSOverlapRate->setValue(0.300000000000000);
        KFPCSEpsilon = new QDoubleSpinBox(widgetKFPCS);
        KFPCSEpsilon->setObjectName(QString::fromUtf8("KFPCSEpsilon"));
        KFPCSEpsilon->setGeometry(QRect(110, 40, 91, 22));
        KFPCSEpsilon->setDecimals(5);
        KFPCSEpsilon->setMaximum(10.000000000000000);
        KFPCSEpsilon->setSingleStep(0.000100000000000);
        KFPCSEpsilon->setValue(0.000100000000000);
        labelNormalRadius_7 = new QLabel(widgetKFPCS);
        labelNormalRadius_7->setObjectName(QString::fromUtf8("labelNormalRadius_7"));
        labelNormalRadius_7->setGeometry(QRect(10, 130, 91, 16));
        labelTransformationEpsilon_7 = new QLabel(widgetKFPCS);
        labelTransformationEpsilon_7->setObjectName(QString::fromUtf8("labelTransformationEpsilon_7"));
        labelTransformationEpsilon_7->setGeometry(QRect(10, 100, 91, 20));
        labelEuclideanEpsilon_7 = new QLabel(widgetKFPCS);
        labelEuclideanEpsilon_7->setObjectName(QString::fromUtf8("labelEuclideanEpsilon_7"));
        labelEuclideanEpsilon_7->setGeometry(QRect(10, 40, 91, 16));
        KFPCSMaxIterations = new QDoubleSpinBox(widgetKFPCS);
        KFPCSMaxIterations->setObjectName(QString::fromUtf8("KFPCSMaxIterations"));
        KFPCSMaxIterations->setGeometry(QRect(110, 70, 91, 22));
        KFPCSMaxIterations->setDecimals(0);
        KFPCSMaxIterations->setMaximum(10000.000000000000000);
        KFPCSMaxIterations->setSingleStep(1.000000000000000);
        KFPCSMaxIterations->setValue(1500.000000000000000);
        KFPCSDelta = new QDoubleSpinBox(widgetKFPCS);
        KFPCSDelta->setObjectName(QString::fromUtf8("KFPCSDelta"));
        KFPCSDelta->setGeometry(QRect(110, 10, 91, 22));
        KFPCSDelta->setDecimals(5);
        KFPCSDelta->setMaximum(1000.000000000000000);
        KFPCSDelta->setSingleStep(0.100000000000000);
        KFPCSDelta->setValue(0.500000000000000);
        labelMaxCorrespondenceDistance_7 = new QLabel(widgetKFPCS);
        labelMaxCorrespondenceDistance_7->setObjectName(QString::fromUtf8("labelMaxCorrespondenceDistance_7"));
        labelMaxCorrespondenceDistance_7->setGeometry(QRect(10, 70, 91, 16));
        KFPCSLambda = new QDoubleSpinBox(widgetKFPCS);
        KFPCSLambda->setObjectName(QString::fromUtf8("KFPCSLambda"));
        KFPCSLambda->setGeometry(QRect(110, 160, 91, 22));
        KFPCSLambda->setDecimals(5);
        KFPCSLambda->setMaximum(10.000000000000000);
        KFPCSLambda->setSingleStep(0.010000000000000);
        KFPCSLambda->setValue(5.000000000000000);
        labelNormalRadius_11 = new QLabel(widgetKFPCS);
        labelNormalRadius_11->setObjectName(QString::fromUtf8("labelNormalRadius_11"));
        labelNormalRadius_11->setGeometry(QRect(10, 160, 91, 16));
        KFPCSMaxAngleDiff = new QDoubleSpinBox(widgetKFPCS);
        KFPCSMaxAngleDiff->setObjectName(QString::fromUtf8("KFPCSMaxAngleDiff"));
        KFPCSMaxAngleDiff->setGeometry(QRect(110, 190, 91, 22));
        KFPCSMaxAngleDiff->setDecimals(5);
        KFPCSMaxAngleDiff->setMaximum(100.000000000000000);
        KFPCSMaxAngleDiff->setSingleStep(0.100000000000000);
        KFPCSMaxAngleDiff->setValue(45.000000000000000);
        labelNormalRadius_12 = new QLabel(widgetKFPCS);
        labelNormalRadius_12->setObjectName(QString::fromUtf8("labelNormalRadius_12"));
        labelNormalRadius_12->setGeometry(QRect(10, 190, 91, 16));
        widgetSFPCS = new QWidget(locateWidgetClass);
        widgetSFPCS->setObjectName(QString::fromUtf8("widgetSFPCS"));
        widgetSFPCS->setGeometry(QRect(720, 20, 211, 221));
        SFPCSNumberOfSamples = new QDoubleSpinBox(widgetSFPCS);
        SFPCSNumberOfSamples->setObjectName(QString::fromUtf8("SFPCSNumberOfSamples"));
        SFPCSNumberOfSamples->setGeometry(QRect(110, 130, 91, 22));
        SFPCSNumberOfSamples->setDecimals(5);
        SFPCSNumberOfSamples->setMaximum(10000.000000000000000);
        SFPCSNumberOfSamples->setSingleStep(1.000000000000000);
        SFPCSNumberOfSamples->setValue(1000.000000000000000);
        labelMaximumIterations_8 = new QLabel(widgetSFPCS);
        labelMaximumIterations_8->setObjectName(QString::fromUtf8("labelMaximumIterations_8"));
        labelMaximumIterations_8->setGeometry(QRect(10, 10, 91, 16));
        SFPCSOverlapRate = new QDoubleSpinBox(widgetSFPCS);
        SFPCSOverlapRate->setObjectName(QString::fromUtf8("SFPCSOverlapRate"));
        SFPCSOverlapRate->setGeometry(QRect(110, 100, 91, 22));
        SFPCSOverlapRate->setDecimals(5);
        SFPCSOverlapRate->setMaximum(10.000000000000000);
        SFPCSOverlapRate->setSingleStep(0.100000000000000);
        SFPCSOverlapRate->setValue(0.900000000000000);
        SFPCSEpsilon = new QDoubleSpinBox(widgetSFPCS);
        SFPCSEpsilon->setObjectName(QString::fromUtf8("SFPCSEpsilon"));
        SFPCSEpsilon->setGeometry(QRect(110, 40, 91, 22));
        SFPCSEpsilon->setDecimals(5);
        SFPCSEpsilon->setMaximum(10.000000000000000);
        SFPCSEpsilon->setSingleStep(0.000100000000000);
        SFPCSEpsilon->setValue(1.000000000000000);
        labelNormalRadius_8 = new QLabel(widgetSFPCS);
        labelNormalRadius_8->setObjectName(QString::fromUtf8("labelNormalRadius_8"));
        labelNormalRadius_8->setGeometry(QRect(10, 130, 91, 16));
        labelTransformationEpsilon_8 = new QLabel(widgetSFPCS);
        labelTransformationEpsilon_8->setObjectName(QString::fromUtf8("labelTransformationEpsilon_8"));
        labelTransformationEpsilon_8->setGeometry(QRect(10, 100, 91, 20));
        labelEuclideanEpsilon_8 = new QLabel(widgetSFPCS);
        labelEuclideanEpsilon_8->setObjectName(QString::fromUtf8("labelEuclideanEpsilon_8"));
        labelEuclideanEpsilon_8->setGeometry(QRect(10, 40, 91, 16));
        SFPCSMaxIterations = new QDoubleSpinBox(widgetSFPCS);
        SFPCSMaxIterations->setObjectName(QString::fromUtf8("SFPCSMaxIterations"));
        SFPCSMaxIterations->setGeometry(QRect(110, 70, 91, 22));
        SFPCSMaxIterations->setDecimals(0);
        SFPCSMaxIterations->setMaximum(100000.000000000000000);
        SFPCSMaxIterations->setSingleStep(1.000000000000000);
        SFPCSMaxIterations->setValue(10000.000000000000000);
        SFPCSDelta = new QDoubleSpinBox(widgetSFPCS);
        SFPCSDelta->setObjectName(QString::fromUtf8("SFPCSDelta"));
        SFPCSDelta->setGeometry(QRect(110, 10, 91, 22));
        SFPCSDelta->setDecimals(5);
        SFPCSDelta->setMaximum(1000.000000000000000);
        SFPCSDelta->setSingleStep(0.100000000000000);
        SFPCSDelta->setValue(0.500000000000000);
        labelMaxCorrespondenceDistance_8 = new QLabel(widgetSFPCS);
        labelMaxCorrespondenceDistance_8->setObjectName(QString::fromUtf8("labelMaxCorrespondenceDistance_8"));
        labelMaxCorrespondenceDistance_8->setGeometry(QRect(10, 70, 91, 16));
        SFPCSMaxTime = new QDoubleSpinBox(widgetSFPCS);
        SFPCSMaxTime->setObjectName(QString::fromUtf8("SFPCSMaxTime"));
        SFPCSMaxTime->setGeometry(QRect(110, 160, 91, 22));
        SFPCSMaxTime->setDecimals(5);
        SFPCSMaxTime->setMaximum(1000.000000000000000);
        SFPCSMaxTime->setSingleStep(1.000000000000000);
        SFPCSMaxTime->setValue(20.000000000000000);
        labelNormalRadius_13 = new QLabel(widgetSFPCS);
        labelNormalRadius_13->setObjectName(QString::fromUtf8("labelNormalRadius_13"));
        labelNormalRadius_13->setGeometry(QRect(10, 160, 91, 16));
        widgetNICP = new QWidget(locateWidgetClass);
        widgetNICP->setObjectName(QString::fromUtf8("widgetNICP"));
        widgetNICP->setGeometry(QRect(490, 270, 211, 221));
        NICPNormalRadius = new QDoubleSpinBox(widgetNICP);
        NICPNormalRadius->setObjectName(QString::fromUtf8("NICPNormalRadius"));
        NICPNormalRadius->setGeometry(QRect(110, 130, 91, 22));
        NICPNormalRadius->setDecimals(5);
        NICPNormalRadius->setMaximum(1000.000000000000000);
        NICPNormalRadius->setSingleStep(1.000000000000000);
        NICPNormalRadius->setValue(6.000000000000000);
        labelMaximumIterations_9 = new QLabel(widgetNICP);
        labelMaximumIterations_9->setObjectName(QString::fromUtf8("labelMaximumIterations_9"));
        labelMaximumIterations_9->setGeometry(QRect(10, 10, 91, 16));
        NICPMaxDistance = new QDoubleSpinBox(widgetNICP);
        NICPMaxDistance->setObjectName(QString::fromUtf8("NICPMaxDistance"));
        NICPMaxDistance->setGeometry(QRect(110, 100, 91, 22));
        NICPMaxDistance->setDecimals(5);
        NICPMaxDistance->setMaximum(10.000000000000000);
        NICPMaxDistance->setSingleStep(0.010000000000000);
        NICPMaxDistance->setValue(0.100000000000000);
        NICPMaxIterations = new QDoubleSpinBox(widgetNICP);
        NICPMaxIterations->setObjectName(QString::fromUtf8("NICPMaxIterations"));
        NICPMaxIterations->setGeometry(QRect(110, 40, 91, 22));
        NICPMaxIterations->setDecimals(0);
        NICPMaxIterations->setMaximum(10000.000000000000000);
        NICPMaxIterations->setSingleStep(1.000000000000000);
        NICPMaxIterations->setValue(100.000000000000000);
        labelNICPNormalRadius = new QLabel(widgetNICP);
        labelNICPNormalRadius->setObjectName(QString::fromUtf8("labelNICPNormalRadius"));
        labelNICPNormalRadius->setGeometry(QRect(10, 130, 91, 16));
        labelTransformationEpsilon_9 = new QLabel(widgetNICP);
        labelTransformationEpsilon_9->setObjectName(QString::fromUtf8("labelTransformationEpsilon_9"));
        labelTransformationEpsilon_9->setGeometry(QRect(10, 100, 91, 20));
        labelEuclideanEpsilon_9 = new QLabel(widgetNICP);
        labelEuclideanEpsilon_9->setObjectName(QString::fromUtf8("labelEuclideanEpsilon_9"));
        labelEuclideanEpsilon_9->setGeometry(QRect(10, 40, 91, 16));
        NICPTransEpsilon = new QDoubleSpinBox(widgetNICP);
        NICPTransEpsilon->setObjectName(QString::fromUtf8("NICPTransEpsilon"));
        NICPTransEpsilon->setGeometry(QRect(110, 70, 91, 22));
        NICPTransEpsilon->setDecimals(5);
        NICPTransEpsilon->setMaximum(10.000000000000000);
        NICPTransEpsilon->setSingleStep(0.000010000000000);
        NICPTransEpsilon->setValue(0.000010000000000);
        NICPEulideanEpsilon = new QDoubleSpinBox(widgetNICP);
        NICPEulideanEpsilon->setObjectName(QString::fromUtf8("NICPEulideanEpsilon"));
        NICPEulideanEpsilon->setGeometry(QRect(110, 10, 91, 22));
        NICPEulideanEpsilon->setDecimals(5);
        NICPEulideanEpsilon->setMaximum(10.000000000000000);
        NICPEulideanEpsilon->setSingleStep(0.010000000000000);
        NICPEulideanEpsilon->setValue(0.100000000000000);
        labelMaxCorrespondenceDistance_9 = new QLabel(widgetNICP);
        labelMaxCorrespondenceDistance_9->setObjectName(QString::fromUtf8("labelMaxCorrespondenceDistance_9"));
        labelMaxCorrespondenceDistance_9->setGeometry(QRect(10, 70, 91, 16));
        widgetICP = new QWidget(locateWidgetClass);
        widgetICP->setObjectName(QString::fromUtf8("widgetICP"));
        widgetICP->setGeometry(QRect(260, 270, 211, 221));
        labelICPEulideanEpsilon = new QLabel(widgetICP);
        labelICPEulideanEpsilon->setObjectName(QString::fromUtf8("labelICPEulideanEpsilon"));
        labelICPEulideanEpsilon->setGeometry(QRect(10, 10, 91, 16));
        ICPMaxDistance = new QDoubleSpinBox(widgetICP);
        ICPMaxDistance->setObjectName(QString::fromUtf8("ICPMaxDistance"));
        ICPMaxDistance->setGeometry(QRect(110, 100, 91, 22));
        ICPMaxDistance->setDecimals(5);
        ICPMaxDistance->setMaximum(10.000000000000000);
        ICPMaxDistance->setSingleStep(0.010000000000000);
        ICPMaxDistance->setValue(0.100000000000000);
        ICPMaxIterations = new QDoubleSpinBox(widgetICP);
        ICPMaxIterations->setObjectName(QString::fromUtf8("ICPMaxIterations"));
        ICPMaxIterations->setGeometry(QRect(110, 40, 91, 22));
        ICPMaxIterations->setDecimals(0);
        ICPMaxIterations->setMaximum(10000.000000000000000);
        ICPMaxIterations->setSingleStep(1.000000000000000);
        ICPMaxIterations->setValue(100.000000000000000);
        labelTransformationEpsilon_12 = new QLabel(widgetICP);
        labelTransformationEpsilon_12->setObjectName(QString::fromUtf8("labelTransformationEpsilon_12"));
        labelTransformationEpsilon_12->setGeometry(QRect(10, 100, 91, 20));
        labelEuclideanEpsilon_12 = new QLabel(widgetICP);
        labelEuclideanEpsilon_12->setObjectName(QString::fromUtf8("labelEuclideanEpsilon_12"));
        labelEuclideanEpsilon_12->setGeometry(QRect(10, 40, 91, 16));
        ICPTransEpsilon = new QDoubleSpinBox(widgetICP);
        ICPTransEpsilon->setObjectName(QString::fromUtf8("ICPTransEpsilon"));
        ICPTransEpsilon->setGeometry(QRect(110, 70, 91, 22));
        ICPTransEpsilon->setDecimals(5);
        ICPTransEpsilon->setMaximum(10.000000000000000);
        ICPTransEpsilon->setSingleStep(0.000010000000000);
        ICPTransEpsilon->setValue(0.000010000000000);
        ICPEulideanEpsilon = new QDoubleSpinBox(widgetICP);
        ICPEulideanEpsilon->setObjectName(QString::fromUtf8("ICPEulideanEpsilon"));
        ICPEulideanEpsilon->setGeometry(QRect(110, 10, 91, 22));
        ICPEulideanEpsilon->setDecimals(5);
        ICPEulideanEpsilon->setMaximum(10.000000000000000);
        ICPEulideanEpsilon->setSingleStep(0.010000000000000);
        ICPEulideanEpsilon->setValue(0.100000000000000);
        labelMaxCorrespondenceDistance_12 = new QLabel(widgetICP);
        labelMaxCorrespondenceDistance_12->setObjectName(QString::fromUtf8("labelMaxCorrespondenceDistance_12"));
        labelMaxCorrespondenceDistance_12->setGeometry(QRect(10, 70, 91, 16));

        retranslateUi(locateWidgetClass);

        QMetaObject::connectSlotsByName(locateWidgetClass);
    } // setupUi

    void retranslateUi(QWidget *locateWidgetClass)
    {
        locateWidgetClass->setWindowTitle(QCoreApplication::translate("locateWidgetClass", "locateWidget", nullptr));
        groupBoxInit->setTitle(QCoreApplication::translate("locateWidgetClass", "\350\216\267\345\217\226\347\202\271\344\272\221", nullptr));
        btnOpenCADPointCloud->setText(QCoreApplication::translate("locateWidgetClass", "\350\257\273\345\217\226CAD\347\202\271\344\272\221", nullptr));
        btnCapturePointCloud->setText(QCoreApplication::translate("locateWidgetClass", "\350\216\267\345\217\226\345\267\245\344\273\266\347\202\271\344\272\221", nullptr));
        checkBoxTestPointCloud->setText(QCoreApplication::translate("locateWidgetClass", "\345\212\240\350\275\275\346\265\213\350\257\225\347\202\271\344\272\221", nullptr));
        groupBoxRegisPara->setTitle(QCoreApplication::translate("locateWidgetClass", "\351\205\215\345\207\206\347\256\227\346\263\225\345\217\212\345\217\202\346\225\260\350\256\276\347\275\256", nullptr));
        comboBoxRegisMethod->setItemText(0, QCoreApplication::translate("locateWidgetClass", "Rough", nullptr));
        comboBoxRegisMethod->setItemText(1, QCoreApplication::translate("locateWidgetClass", "Precise", nullptr));

        comboBoxPreciseRegisMethod->setItemText(0, QCoreApplication::translate("locateWidgetClass", "ICP", nullptr));
        comboBoxPreciseRegisMethod->setItemText(1, QCoreApplication::translate("locateWidgetClass", "NICP", nullptr));

        comboBoxRoughRegisMethod->setItemText(0, QCoreApplication::translate("locateWidgetClass", "FPCS", nullptr));
        comboBoxRoughRegisMethod->setItemText(1, QCoreApplication::translate("locateWidgetClass", "KFPCS", nullptr));
        comboBoxRoughRegisMethod->setItemText(2, QCoreApplication::translate("locateWidgetClass", "SFPCS", nullptr));

        groupBoxRegisControl->setTitle(QCoreApplication::translate("locateWidgetClass", "\347\202\271\344\272\221\351\205\215\345\207\206", nullptr));
        btnStartRoughRegis->setText(QCoreApplication::translate("locateWidgetClass", "\347\262\227\351\205\215\345\207\206", nullptr));
        btnStartPreciseRegis->setText(QCoreApplication::translate("locateWidgetClass", "\347\262\276\351\205\215\345\207\206", nullptr));
        groupBoxPointCloudPreProcess->setTitle(QCoreApplication::translate("locateWidgetClass", "\347\202\271\344\272\221\351\242\204\345\244\204\347\220\206", nullptr));
        btnDownsample->setText(QCoreApplication::translate("locateWidgetClass", "\347\202\271\344\272\221\351\231\215\351\207\207\346\240\267", nullptr));
        btnFilter->setText(QCoreApplication::translate("locateWidgetClass", "\347\202\271\344\272\221\346\273\244\346\263\242", nullptr));
        labelRadius->setText(QCoreApplication::translate("locateWidgetClass", "\345\215\212\345\276\204\357\274\232", nullptr));
        labelMinNeighborsInRadius->setText(QCoreApplication::translate("locateWidgetClass", "\346\234\200\345\260\217\350\277\221\351\202\273\350\267\235\347\246\273\357\274\232", nullptr));
        labelDownsample->setText(QCoreApplication::translate("locateWidgetClass", "CAD\347\202\271\344\272\221\351\231\215\351\207\207\346\240\267", nullptr));
        labelDownsample_2->setText(QCoreApplication::translate("locateWidgetClass", "\345\267\245\344\273\266\347\202\271\344\272\221\351\231\215\351\207\207\346\240\267", nullptr));
        labelMaximumIterations_6->setText(QCoreApplication::translate("locateWidgetClass", "Delta", nullptr));
        labelNormalRadius_6->setText(QCoreApplication::translate("locateWidgetClass", "NumberOfSamples", nullptr));
        labelTransformationEpsilon_6->setText(QCoreApplication::translate("locateWidgetClass", "OverlapRate", nullptr));
        labelEuclideanEpsilon_6->setText(QCoreApplication::translate("locateWidgetClass", "Epsilon", nullptr));
        labelMaxCorrespondenceDistance_6->setText(QCoreApplication::translate("locateWidgetClass", "MaxIterations", nullptr));
        labelNormalRadius_9->setText(QCoreApplication::translate("locateWidgetClass", "NumberOfThreads", nullptr));
        labelKFPCSDelta->setText(QCoreApplication::translate("locateWidgetClass", "Delta", nullptr));
        labelNormalRadius_7->setText(QCoreApplication::translate("locateWidgetClass", "NumberOfSamples", nullptr));
        labelTransformationEpsilon_7->setText(QCoreApplication::translate("locateWidgetClass", "OverlapRate", nullptr));
        labelEuclideanEpsilon_7->setText(QCoreApplication::translate("locateWidgetClass", "Epsilon", nullptr));
        labelMaxCorrespondenceDistance_7->setText(QCoreApplication::translate("locateWidgetClass", "MaxIterations", nullptr));
        labelNormalRadius_11->setText(QCoreApplication::translate("locateWidgetClass", "Lambda", nullptr));
        labelNormalRadius_12->setText(QCoreApplication::translate("locateWidgetClass", "MaxAngleDiff", nullptr));
        labelMaximumIterations_8->setText(QCoreApplication::translate("locateWidgetClass", "Delta", nullptr));
        labelNormalRadius_8->setText(QCoreApplication::translate("locateWidgetClass", "NumberOfSamples", nullptr));
        labelTransformationEpsilon_8->setText(QCoreApplication::translate("locateWidgetClass", "OverlapRate", nullptr));
        labelEuclideanEpsilon_8->setText(QCoreApplication::translate("locateWidgetClass", "Epsilon", nullptr));
        labelMaxCorrespondenceDistance_8->setText(QCoreApplication::translate("locateWidgetClass", "MaxIterations", nullptr));
        labelNormalRadius_13->setText(QCoreApplication::translate("locateWidgetClass", "MaxTime", nullptr));
        labelMaximumIterations_9->setText(QCoreApplication::translate("locateWidgetClass", "EulideanEpsilon", nullptr));
        labelNICPNormalRadius->setText(QCoreApplication::translate("locateWidgetClass", "NormalRadius", nullptr));
        labelTransformationEpsilon_9->setText(QCoreApplication::translate("locateWidgetClass", "MaxDistance", nullptr));
        labelEuclideanEpsilon_9->setText(QCoreApplication::translate("locateWidgetClass", "MaxIterations", nullptr));
        labelMaxCorrespondenceDistance_9->setText(QCoreApplication::translate("locateWidgetClass", "TransEpsilon", nullptr));
        labelICPEulideanEpsilon->setText(QCoreApplication::translate("locateWidgetClass", "EulideanEpsilon", nullptr));
        labelTransformationEpsilon_12->setText(QCoreApplication::translate("locateWidgetClass", "MaxDistance", nullptr));
        labelEuclideanEpsilon_12->setText(QCoreApplication::translate("locateWidgetClass", "MaxIterations", nullptr));
        labelMaxCorrespondenceDistance_12->setText(QCoreApplication::translate("locateWidgetClass", "TransEpsilon", nullptr));
    } // retranslateUi

};

namespace Ui {
    class locateWidgetClass: public Ui_locateWidgetClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LOCATEWIDGET_H
